packages:
  - apps/*
  - packages/*

catalog:
  '@reduxjs/toolkit': ^2.8.2
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  react: ^19.1.0
  react-dom: ^19.1.0
  react-redux: ^9.2.0
  typescript: 5.8.3
  vite: ^7.0.4
