packages:
  - "apps/*"
  - "packages/*"
# Define a catalog of version ranges.
catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.0.14
  "@types/react-dom": ^19.0.6
  "typescript": ^5.8.3
  "vite": ^7.0.4
